name: Aquaman
main: XanderID\Aquaman\Aquaman
version: 1.0.0
api: 4.0.0
description: now you can breathe in water without limit
author: XanderID

permissions:
 aquaman.transform:
  default: op
  description: Transform Into Aquaman
